/*
 @licstart  The following is the entire license notice for the JavaScript code in this file.

 The MIT License (MIT)

 Copyright (C) 1997-2020 by Dimitri van Heesch

 Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 and associated documentation files (the "Software"), to deal in the Software without restriction,
 including without limitation the rights to use, copy, modify, merge, publish, distribute,
 sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all copies or
 substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 @licend  The above is the entire license notice for the JavaScript code in this file
*/
var menudata={children:[
{text:"Main Page",url:"index.html"},
{text:"Classes",url:"annotated.html",children:[
{text:"Class List",url:"annotated.html"},
{text:"Class Index",url:"classes.html"},
{text:"Class Hierarchy",url:"hierarchy.html"},
{text:"Class Members",url:"functions.html",children:[
{text:"All",url:"functions.html",children:[
{text:"b",url:"functions.html#index_b"},
{text:"c",url:"functions.html#index_c"},
{text:"e",url:"functions.html#index_e"},
{text:"i",url:"functions.html#index_i"},
{text:"m",url:"functions.html#index_m"},
{text:"p",url:"functions.html#index_p"},
{text:"z",url:"functions.html#index_z"},
{text:"~",url:"functions.html#index__7E"}]},
{text:"Functions",url:"functions_func.html",children:[
{text:"e",url:"functions_func.html#index_e"},
{text:"i",url:"functions_func.html#index_i"},
{text:"m",url:"functions_func.html#index_m"},
{text:"p",url:"functions_func.html#index_p"},
{text:"z",url:"functions_func.html#index_z"},
{text:"~",url:"functions_func.html#index__7E"}]},
{text:"Variables",url:"functions_vars.html",children:[
{text:"z",url:"functions_vars.html#index_z"}]},
{text:"Typedefs",url:"functions_type.html"},
{text:"Enumerations",url:"functions_enum.html"},
{text:"Enumerator",url:"functions_eval.html"}]}]},
{text:"Files",url:"files.html",children:[
{text:"File List",url:"files.html"},
{text:"File Members",url:"globals.html",children:[
{text:"All",url:"globals.html",children:[
{text:"",url:"globals.html#index_a0x00"},
{text:"a",url:"globals_a.html#index_a"},
{text:"c",url:"globals_c.html#index_c"},
{text:"d",url:"globals_d.html#index_d"},
{text:"e",url:"globals_e.html#index_e"},
{text:"f",url:"globals_f.html#index_f"},
{text:"g",url:"globals_g.html#index_g"},
{text:"h",url:"globals_h.html#index_h"},
{text:"i",url:"globals_i.html#index_i"},
{text:"k",url:"globals_k.html#index_k"},
{text:"l",url:"globals_l.html#index_l"},
{text:"m",url:"globals_m.html#index_m"},
{text:"n",url:"globals_n.html#index_n"},
{text:"o",url:"globals_o.html#index_o"},
{text:"p",url:"globals_p.html#index_p"},
{text:"r",url:"globals_r.html#index_r"},
{text:"s",url:"globals_s.html#index_s"},
{text:"t",url:"globals_t.html#index_t"},
{text:"u",url:"globals_u.html#index_u"},
{text:"v",url:"globals_v.html#index_v"},
{text:"w",url:"globals_w.html#index_w"},
{text:"y",url:"globals_y.html#index_y"},
{text:"z",url:"globals_z.html#index_z"},
{text:"",url:"globals_0x9b.html#index_a0x9b"},
{text:"«",url:"globals_0xab.html#index_a0xab"},
{text:"Á",url:"globals_0xc1.html#index_a0xc1"},
{text:"ʠ",url:"globals_0x02a0.html#index_a0x02a0"},
{text:"ʰ",url:"globals_0x02b0.html#index_a0x02b0"},
{text:"ˈ",url:"globals_0x02c8.html#index_a0x02c8"},
{text:"˨",url:"globals_0x02e8.html#index_a0x02e8"},
{text:"ͅ",url:"globals_0x0345.html#index_a0x0345"},
{text:"͠",url:"globals_0x0360.html#index_a0x0360"},
{text:"΁",url:"globals_0x0381.html#index_a0x0381"},
{text:"Τ",url:"globals_0x03a4.html#index_a0x03a4"},
{text:"ώ",url:"globals_0x03ce.html#index_a0x03ce"},
{text:"ϐ",url:"globals_0x03d0.html#index_a0x03d0"},
{text:"ϰ",url:"globals_0x03f0.html#index_a0x03f0"},
{text:"Ѐ",url:"globals_0x0400.html#index_a0x0400"},
{text:"Ѕ",url:"globals_0x0405.html#index_a0x0405"},
{text:"Ј",url:"globals_0x0408.html#index_a0x0408"},
{text:"ђ",url:"globals_0x0452.html#index_a0x0452"},
{text:"Ӂ",url:"globals_0x04c1.html#index_a0x04c1"},
{text:"Ԏ",url:"globals_0x050e.html#index_a0x050e"},
{text:"օ",url:"globals_0x0585.html#index_a0x0585"},
{text:"ࡧ",url:"globals_0x0867.html#index_a0x0867"},
{text:"ᨡ",url:"globals_0x1a21.html#index_a0x1a21"},
{text:"⥰",url:"globals_0x2970.html#index_a0x2970"},
{text:"⮱",url:"globals_0x2bb1.html#index_a0x2bb1"},
{text:"㠰",url:"globals_0x3830.html#index_a0x3830"},
{text:"㮱",url:"globals_0x3bb1.html#index_a0x3bb1"},
{text:"䠭",url:"globals_0x482d.html#index_a0x482d"},
{text:"䮱",url:"globals_0x4bb1.html#index_a0x4bb1"},
{text:"砤",url:"globals_0x7824.html#index_a0x7824"},
{text:"砪",url:"globals_0x782a.html#index_a0x782a"},
{text:"筠",url:"globals_0x7b60.html#index_a0x7b60"},
{text:"觬",url:"globals_0x89ec.html#index_a0x89ec"},
{text:"豪",url:"globals_0x8c6a.html#index_a0x8c6a"},
{text:"ꮤ",url:"globals_0xaba4.html#index_a0xaba4"},
{text:"먶",url:"globals_0xba36.html#index_a0xba36"},
{text:"젲",url:"globals_0xc832.html#index_a0xc832"},
{text:"쥱",url:"globals_0xc971.html#index_a0xc971"},
{text:"쮤",url:"globals_0xcba4.html#index_a0xcba4"},
{text:"���",url:"globals_0xd830.html#index_a0xd830"},
{text:"���",url:"globals_0xd965.html#index_a0xd965"},
{text:"���",url:"globals_0xd96f.html#index_a0xd96f"},
{text:"���",url:"globals_0xd972.html#index_a0xd972"},
{text:"���",url:"globals_0xdbac.html#index_a0xdbac"},
{text:"���",url:"globals_0xdbb0.html#index_a0xdbb0"},
{text:"���",url:"globals_0xdbb1.html#index_a0xdbb1"},
{text:"���",url:"globals_0xdce6.html#index_a0xdce6"},
{text:"",url:"globals_0xe865.html#index_a0xe865"},
{text:"",url:"globals_0xe870.html#index_a0xe870"},
{text:"",url:"globals_0xe871.html#index_a0xe871"},
{text:"",url:"globals_0xe87a.html#index_a0xe87a"},
{text:"",url:"globals_0xe87f.html#index_a0xe87f"},
{text:"",url:"globals_0xe8f0.html#index_a0xe8f0"},
{text:"",url:"globals_0xecad.html#index_a0xecad"},
{text:"",url:"globals_0xf830.html#index_a0xf830"},
{text:"殺",url:"globals_0xf970.html#index_a0xf970"},
{text:"﫠",url:"globals_0xfae0.html#index_a0xfae0"},
{text:"ﮤ",url:"globals_0xfba4.html#index_a0xfba4"},
{text:"ﮦ",url:"globals_0xfba6.html#index_a0xfba6"},
{text:"ﮫ",url:"globals_0xfbab.html#index_a0xfbab"},
{text:"ﰠ",url:"globals_0xfc20.html#index_a0xfc20"},
{text:"ﰨ",url:"globals_0xfc28.html#index_a0xfc28"},
{text:"ﰮ",url:"globals_0xfc2e.html#index_a0xfc2e"},
{text:"ﳭ",url:"globals_0xfced.html#index_a0xfced"},
{text:"౯",url:"globals_0x020c6f.html#index_a0x020c6f"},
{text:"豲",url:"globals_0x068c72.html#index_a0x068c72"},
{text:"볷",url:"globals_0x06bcf7.html#index_a0x06bcf7"},
{text:"",url:"globals_0x06e8eb.html#index_a0x06e8eb"},
{text:"।",url:"globals_0x070964.html#index_a0x070964"},
{text:"ừ",url:"globals_0x071eeb.html#index_a0x071eeb"},
{text:"㤠",url:"globals_0x073920.html#index_a0x073920"},
{text:"媱",url:"globals_0x0a5ab1.html#index_a0x0a5ab1"},
{text:"",url:"globals_0x0ae8e4.html#index_a0x0ae8e4"},
{text:"",url:"globals_0x0ae8ee.html#index_a0x0ae8ee"},
{text:"",url:"globals_0x0aeb33.html#index_a0x0aeb33"},
{text:"ॡ",url:"globals_0x0b0961.html#index_a0x0b0961"},
{text:"⥤",url:"globals_0x0e2964.html#index_a0x0e2964"},
{text:"䮱",url:"globals_0x0e4bb1.html#index_a0x0e4bb1"},
{text:"ꠧ",url:"globals_0x0ea827.html#index_a0x0ea827"},
{text:"᫮",url:"globals_0x0f1aee.html#index_a0x0f1aee"},
{text:"⨫",url:"globals_0x0f2a2b.html#index_a0x0f2a2b"},
{text:"੫",url:"globals_0x120a6b.html#index_a0x120a6b"},
{text:"",url:"globals_0x12ec2c.html#index_a0x12ec2c"},
{text:"㭪",url:"globals_0x133b6a.html#index_a0x133b6a"},
{text:"嫨",url:"globals_0x1a5ae8.html#index_a0x1a5ae8"},
{text:"嫮",url:"globals_0x1a5aee.html#index_a0x1a5aee"},
{text:"嫿",url:"globals_0x1a5aff.html#index_a0x1a5aff"},
{text:"౲",url:"globals_0x1e0c72.html#index_a0x1e0c72"}]},
{text:"Functions",url:"globals_func.html",children:[
{text:"a",url:"globals_func.html#index_a"},
{text:"d",url:"globals_func.html#index_d"},
{text:"f",url:"globals_func.html#index_f"},
{text:"g",url:"globals_func.html#index_g"},
{text:"i",url:"globals_func.html#index_i"},
{text:"l",url:"globals_func.html#index_l"},
{text:"m",url:"globals_func.html#index_m"},
{text:"r",url:"globals_func.html#index_r"},
{text:"w",url:"globals_func.html#index_w"},
{text:"y",url:"globals_func.html#index_y"},
{text:"Á",url:"globals_func.html#index_a0xc1"},
{text:"ϰ",url:"globals_func.html#index_a0x03f0"},
{text:"Ӂ",url:"globals_func.html#index_a0x04c1"},
{text:"䠭",url:"globals_func.html#index_a0x482d"},
{text:"���",url:"globals_func.html#index_a0xd830"},
{text:"���",url:"globals_func.html#index_a0xd972"},
{text:"ﰮ",url:"globals_func.html#index_a0xfc2e"},
{text:"౯",url:"globals_func.html#index_a0x020c6f"},
{text:"",url:"globals_func.html#index_a0x06e8eb"},
{text:"੫",url:"globals_func.html#index_a0x120a6b"},
{text:"㭪",url:"globals_func.html#index_a0x133b6a"}]},
{text:"Variables",url:"globals_vars.html",children:[
{text:"",url:"globals_vars.html#index_a0x00"},
{text:"a",url:"globals_vars_a.html#index_a"},
{text:"c",url:"globals_vars_c.html#index_c"},
{text:"d",url:"globals_vars_d.html#index_d"},
{text:"e",url:"globals_vars_e.html#index_e"},
{text:"f",url:"globals_vars_f.html#index_f"},
{text:"g",url:"globals_vars_g.html#index_g"},
{text:"h",url:"globals_vars_h.html#index_h"},
{text:"i",url:"globals_vars_i.html#index_i"},
{text:"k",url:"globals_vars_k.html#index_k"},
{text:"l",url:"globals_vars_l.html#index_l"},
{text:"m",url:"globals_vars_m.html#index_m"},
{text:"n",url:"globals_vars_n.html#index_n"},
{text:"o",url:"globals_vars_o.html#index_o"},
{text:"p",url:"globals_vars_p.html#index_p"},
{text:"r",url:"globals_vars_r.html#index_r"},
{text:"s",url:"globals_vars_s.html#index_s"},
{text:"t",url:"globals_vars_t.html#index_t"},
{text:"u",url:"globals_vars_u.html#index_u"},
{text:"v",url:"globals_vars_v.html#index_v"},
{text:"w",url:"globals_vars_w.html#index_w"},
{text:"y",url:"globals_vars_y.html#index_y"},
{text:"",url:"globals_vars_0x9b.html#index_a0x9b"},
{text:"«",url:"globals_vars_0xab.html#index_a0xab"},
{text:"Á",url:"globals_vars_0xc1.html#index_a0xc1"},
{text:"ʠ",url:"globals_vars_0x02a0.html#index_a0x02a0"},
{text:"ʰ",url:"globals_vars_0x02b0.html#index_a0x02b0"},
{text:"ˈ",url:"globals_vars_0x02c8.html#index_a0x02c8"},
{text:"˨",url:"globals_vars_0x02e8.html#index_a0x02e8"},
{text:"ͅ",url:"globals_vars_0x0345.html#index_a0x0345"},
{text:"͠",url:"globals_vars_0x0360.html#index_a0x0360"},
{text:"΁",url:"globals_vars_0x0381.html#index_a0x0381"},
{text:"Τ",url:"globals_vars_0x03a4.html#index_a0x03a4"},
{text:"ώ",url:"globals_vars_0x03ce.html#index_a0x03ce"},
{text:"ϐ",url:"globals_vars_0x03d0.html#index_a0x03d0"},
{text:"ϰ",url:"globals_vars_0x03f0.html#index_a0x03f0"},
{text:"Ѐ",url:"globals_vars_0x0400.html#index_a0x0400"},
{text:"Ѕ",url:"globals_vars_0x0405.html#index_a0x0405"},
{text:"Ј",url:"globals_vars_0x0408.html#index_a0x0408"},
{text:"ђ",url:"globals_vars_0x0452.html#index_a0x0452"},
{text:"Ӂ",url:"globals_vars_0x04c1.html#index_a0x04c1"},
{text:"Ԏ",url:"globals_vars_0x050e.html#index_a0x050e"},
{text:"օ",url:"globals_vars_0x0585.html#index_a0x0585"},
{text:"ࡧ",url:"globals_vars_0x0867.html#index_a0x0867"},
{text:"ᨡ",url:"globals_vars_0x1a21.html#index_a0x1a21"},
{text:"⥰",url:"globals_vars_0x2970.html#index_a0x2970"},
{text:"⮱",url:"globals_vars_0x2bb1.html#index_a0x2bb1"},
{text:"㠰",url:"globals_vars_0x3830.html#index_a0x3830"},
{text:"㮱",url:"globals_vars_0x3bb1.html#index_a0x3bb1"},
{text:"䠭",url:"globals_vars_0x482d.html#index_a0x482d"},
{text:"䮱",url:"globals_vars_0x4bb1.html#index_a0x4bb1"},
{text:"砤",url:"globals_vars_0x7824.html#index_a0x7824"},
{text:"砪",url:"globals_vars_0x782a.html#index_a0x782a"},
{text:"筠",url:"globals_vars_0x7b60.html#index_a0x7b60"},
{text:"觬",url:"globals_vars_0x89ec.html#index_a0x89ec"},
{text:"豪",url:"globals_vars_0x8c6a.html#index_a0x8c6a"},
{text:"ꮤ",url:"globals_vars_0xaba4.html#index_a0xaba4"},
{text:"먶",url:"globals_vars_0xba36.html#index_a0xba36"},
{text:"젲",url:"globals_vars_0xc832.html#index_a0xc832"},
{text:"쥱",url:"globals_vars_0xc971.html#index_a0xc971"},
{text:"쮤",url:"globals_vars_0xcba4.html#index_a0xcba4"},
{text:"���",url:"globals_vars_0xd965.html#index_a0xd965"},
{text:"���",url:"globals_vars_0xd96f.html#index_a0xd96f"},
{text:"���",url:"globals_vars_0xdbac.html#index_a0xdbac"},
{text:"���",url:"globals_vars_0xdbb0.html#index_a0xdbb0"},
{text:"���",url:"globals_vars_0xdbb1.html#index_a0xdbb1"},
{text:"���",url:"globals_vars_0xdce6.html#index_a0xdce6"},
{text:"",url:"globals_vars_0xe865.html#index_a0xe865"},
{text:"",url:"globals_vars_0xe870.html#index_a0xe870"},
{text:"",url:"globals_vars_0xe871.html#index_a0xe871"},
{text:"",url:"globals_vars_0xe87a.html#index_a0xe87a"},
{text:"",url:"globals_vars_0xe87f.html#index_a0xe87f"},
{text:"",url:"globals_vars_0xe8f0.html#index_a0xe8f0"},
{text:"",url:"globals_vars_0xecad.html#index_a0xecad"},
{text:"",url:"globals_vars_0xf830.html#index_a0xf830"},
{text:"殺",url:"globals_vars_0xf970.html#index_a0xf970"},
{text:"﫠",url:"globals_vars_0xfae0.html#index_a0xfae0"},
{text:"ﮤ",url:"globals_vars_0xfba4.html#index_a0xfba4"},
{text:"ﮦ",url:"globals_vars_0xfba6.html#index_a0xfba6"},
{text:"ﮫ",url:"globals_vars_0xfbab.html#index_a0xfbab"},
{text:"ﰠ",url:"globals_vars_0xfc20.html#index_a0xfc20"},
{text:"ﰨ",url:"globals_vars_0xfc28.html#index_a0xfc28"},
{text:"ﰮ",url:"globals_vars_0xfc2e.html#index_a0xfc2e"},
{text:"ﳭ",url:"globals_vars_0xfced.html#index_a0xfced"},
{text:"౯",url:"globals_vars_0x020c6f.html#index_a0x020c6f"},
{text:"豲",url:"globals_vars_0x068c72.html#index_a0x068c72"},
{text:"볷",url:"globals_vars_0x06bcf7.html#index_a0x06bcf7"},
{text:"।",url:"globals_vars_0x070964.html#index_a0x070964"},
{text:"ừ",url:"globals_vars_0x071eeb.html#index_a0x071eeb"},
{text:"㤠",url:"globals_vars_0x073920.html#index_a0x073920"},
{text:"媱",url:"globals_vars_0x0a5ab1.html#index_a0x0a5ab1"},
{text:"",url:"globals_vars_0x0ae8e4.html#index_a0x0ae8e4"},
{text:"",url:"globals_vars_0x0ae8ee.html#index_a0x0ae8ee"},
{text:"",url:"globals_vars_0x0aeb33.html#index_a0x0aeb33"},
{text:"ॡ",url:"globals_vars_0x0b0961.html#index_a0x0b0961"},
{text:"⥤",url:"globals_vars_0x0e2964.html#index_a0x0e2964"},
{text:"䮱",url:"globals_vars_0x0e4bb1.html#index_a0x0e4bb1"},
{text:"ꠧ",url:"globals_vars_0x0ea827.html#index_a0x0ea827"},
{text:"᫮",url:"globals_vars_0x0f1aee.html#index_a0x0f1aee"},
{text:"⨫",url:"globals_vars_0x0f2a2b.html#index_a0x0f2a2b"},
{text:"੫",url:"globals_vars_0x120a6b.html#index_a0x120a6b"},
{text:"",url:"globals_vars_0x12ec2c.html#index_a0x12ec2c"},
{text:"嫨",url:"globals_vars_0x1a5ae8.html#index_a0x1a5ae8"},
{text:"嫮",url:"globals_vars_0x1a5aee.html#index_a0x1a5aee"},
{text:"嫿",url:"globals_vars_0x1a5aff.html#index_a0x1a5aff"},
{text:"౲",url:"globals_vars_0x1e0c72.html#index_a0x1e0c72"}]},
{text:"Macros",url:"globals_defs.html"}]}]}]}
